#!/usr/bin/env bash

set -e

usage() {
cat << EOF
USAGE:

   notes [year|"all"] [quarter]

EXAMPLES:

   notes
      compiles notes for current year/quarter

   notes all
      compiles all notes

   notes 2020
      compiles notes for year 2020

   notes 2018 3
      compiles notes for year 2018 quarter 3

EOF
}

getnotes() {
   ack -n "> Date: " . | \
   while read line; do
      topic=$(echo "$line" | sed 's/\([^ ]*\) .*/\1/')
      file=$(echo "$line" | sed 's/\([^:]*\):2:>.*$/\1/')
      date=$(echo "$line" | sed 's/[^:]*:2:> Date: \(.*$\)/\1/')
      echo "$topic$date $file"
   done | \
   sort -n | \
   while read line; do
      file=$(echo "$line" | sed 's/[^ ]* \(.*\)/\1/')
      echo "$file"
   done
   unset topic file date
}

makepdf() {
   pandoc --pdf-engine=xelatex -s -H $NOTES_DIR/font.tex --toc \
         -o "${1}.pdf" $2 &&
   echo "Created ${1}.pdf"
}

makehtml() {
    pandoc -s --webtex --metadata title=$(basename $2) -i -t slidy $2 -o "${1}.html" &&
   echo "Created ${1}.html"
}

makenotes() {
   for year in $NOTES_DIR/year$1; do
      for quarter in $year/q$2; do
         cd "$quarter"
         notes=$(getnotes)
         output_file="$quarter/"$(basename "$quarter")

         oldifs=$IFS
         IFS=$'\n'

         makepdf "$output_file" "$notes"
         makehtml "$output_file" "$notes"

         IFS=$oldifs

         unset notes output_file oldifs
         cd - &>/dev/null
      done
      cd "$year"
      echo "Compiling ${year}.pdf..."
      gs -sDEVICE=pdfwrite \
         -dQUIET \
         -o "$(basename $year).pdf" \
         q*/*.pdf &&
         echo "Created ${year}.pdf"
      cd - &>/dev/null
   done
}

main() {
   case "$1" in
      "all") echo "Compiling all notes..." && makenotes "*" "*"; exit 0;;
      '') echo "Compiling year$YEAR/q${QUARTER}..." && makenotes $YEAR $QUARTER; exit 0;;
      [0-9]*)
         if [[ "$2" = [1-4]* ]]; then
            echo "Compiling year$1/q${2}..."
            makenotes "$1" "$2"
         elif [[ "$2" == "" ]]; then
            echo "Compiling year${1}..."
            makenotes "$1" "*"
         else
            usage; exit 1
         fi
         exit 0;;
      *) usage; exit 1;;
   esac
}

main "$1" "$2"
